export const ADD_COUNTRY_LIST = 'ADD_COUNTRY_LIST'
export const CHANGE_SELECT_COUNTRY = 'CHANGE_SELECT_COUNTRY'
export const RESET_SELECT_COUNTRY = 'RESET_SELECT_COUNTRY'


export const CHANGE_STARS_COUNT = 'CHANGE_STARS_COUNT'
export const CHANGE_STAR_SELECT = 'CHANGE_STAR_SELECT'
export const RESET_STAR_SELECT = 'RESET_STAR_SELECT'


export const CHANGE_TYPE_SELECT = 'CHANGE_TYPE_SELECT'
export const RESET_TYPE_SELECT = 'RESET_TYPE_SELECT'


export const CHANGE_REVIEWS_COUNT = 'CHANGE_REVIEWS_COUNT'
export const RESET_REVIEWS_COUNT = 'RESET_REVIEWS_COUNT'


export const CHANGE_MIN_PRICE = 'CHANGE_MIN_PRICE'
export const CHANGE_MAX_PRICE = 'CHANGE_MAX_PRICE'
export const RESET_PRICE_FILTER = 'RESET_PRICE_FILTER'

export const SET_HOTELS_LIST = 'SET_HOTELS_LIST'