export const ADD_COUNTRY_LIST = 'ADD_COUNTRY_LIST'
export const CHANGE_SELECT_COUNTRY = 'CHANGE_SELECT_COUNTRY'

export const CHANGE_STARS_COUNT = 'CHANGE_STARS_COUNT'
export const CHANGE_STAR_SELECT = 'CHANGE_STAR_SELECT'

export const CHANGE_TYPE_SELECT = 'CHANGE_TYPE_SELECT'

export const CHANGE_REVIEWS_COUNT = 'CHANGE_REVIEWS_COUNT'
